### ISSUE TITLE
no-url-for-image

### ISSUE THREAD

**Issue by celsomtrindade** [panurge-ws/ng-imago#1]
I'm using ng-imago and trying to populate it with an object from json array.
I'm using it like so:

```
<img ng-imago default="{{product.img}}" imago-resize="{scale:'cover', center:true}" />
```

But i keep getting this alert message:

> [ngImagoModule] -> no-url-for-image Object {default: "", small: undefined, medium: undefined, large: undefined, xlarge: undefined}

**Comment by panurge-ws** [comment]
Are you sure the product.img is populated, it seems it has an empty value.
If you declare the image before the json is loaded, you can have that kind of error until the $scope.product object is populated.

**Comment by celsomtrindade** [comment]
Yes, it's populated because the image shows up. It works like there is no error, but in the console, there is this warning message.

**Comment by panurge-ws** [comment]
It's a warning message dispatched when the data is still not populated but the directive is compiled.
You can turn off warning/log messages according to $log documentation: https://docs.angularjs.org/api/ng/service/$log
